# Generated by Django 5.0.4 on 2024-05-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='products.product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product2', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SavedHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_product1', to='products.product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_product2', to='products.product')),
            ],
        ),
    ]
